# Generated by Django 3.1.4 on 2020-12-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201210_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsname',
            name='language',
            field=models.CharField(choices=[('UZ', 'Uzbek'), ('RU', 'Russian'), ('EN', 'English')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsname',
            name='description',
            field=models.TextField(verbose_name='Description of news'),
        ),
        migrations.AlterField(
            model_name='newsname',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='newsname',
            unique_together={('news', 'language')},
        ),
    ]
