# Generated by Django 3.1.4 on 2020-12-10 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201210_0513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='add_at',
            new_name='added_at',
        ),
    ]
