# Generated by Django 3.1.4 on 2020-12-10 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201210_0520'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='newsname',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tagname',
            unique_together=set(),
        ),
    ]
